/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;

public class App {
    public String analyzeWeather(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        HashSet<Integer> temps = new HashSet();

        for(int[] week : weeklyMonthTemperatures) {
            for (int temp : week) {
                temps.add(temp);
            }
        }

        String result = new String();
        Iterator<Integer> i = temps.iterator();
        while(i.hasNext()){
            result = result + i.next() + " ";
        }
        return result;
    }

    public static void main(String[] args) {
        System.out.println(new App().analyzeWeather());
    }
}
