/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasARoll() {
        App classUnderTest = new App();
        assertNotNull("app should have a roll function", classUnderTest.roll(5));
    }

    @Test
    public void testRoll(){
        int[] rolls = App.roll(1000);
        assertEquals("roll rolls the correct amount of dice", rolls.length, 1000);
        int max = Integer.MIN_VALUE;
        int min = Integer.MAX_VALUE;
        for(int i : rolls){
            if(i < min) min = i;
            if(i > max) max = i;
        }

        assertTrue("roll rolls six sided dice", max <= 6 && min >= 0);
    }
}
